-- Created by Faraz Fookeer: farazfookeer.com
-- ==========================================
-- 1. PARENT TABLES (Must create these first)
-- ==========================================

-- Keeps track of each full simulation execution
CREATE TABLE IF NOT EXISTS sim_runs (
    id SERIAL PRIMARY KEY,
    start_time TIMESTAMP DEFAULT NOW(),
    status VARCHAR(20) DEFAULT 'RUNNING' -- 'RUNNING', 'COMPLETED'
);

-- The Pension Funds (The "Players")
CREATE TABLE IF NOT EXISTS clients (
    client_id VARCHAR(50) PRIMARY KEY, -- e.g., 'PF_ACME_1'
    name VARCHAR(100),
    risk_profile VARCHAR(20) -- 'CONSERVATIVE', 'AGGRESSIVE'
);

-- ==========================================
-- 2. DATA TABLES (The Simulation State)
-- ==========================================

-- Daily Economic Conditions (Generated by Workflow B)
CREATE TABLE IF NOT EXISTS market_daily (
    date DATE PRIMARY KEY,
    nominal_yield_10y DECIMAL(5,2), -- e.g., 4.50
    inflation_expectations DECIMAL(5,2),
    regime VARCHAR(50), -- 'STABLE', 'CRASH', 'BOOM'
    news_headline TEXT
);

-- Daily Liabilities for each Client (Calculated by Workflow C)
CREATE TABLE IF NOT EXISTS liabilities_daily (
    id SERIAL PRIMARY KEY,
    date DATE REFERENCES market_daily(date),
    client_id VARCHAR(50) REFERENCES clients(client_id),
    pv_liabilities DECIMAL(20,2) -- Present Value of what they owe
);

-- Daily Asset Inventory (The Portfolio)
CREATE TABLE IF NOT EXISTS collateral_inventory (
    id SERIAL PRIMARY KEY,
    date DATE,
    client_id VARCHAR(50) REFERENCES clients(client_id),
    asset_type VARCHAR(20), -- 'GILT', 'CASH', 'CORP_BOND'
    quantity DECIMAL(20,2),
    market_price DECIMAL(10,2),
    total_assets DECIMAL(20,2) -- Calculated as qty * price
);

-- ==========================================
-- 3. AGENT OUTPUT TABLES (The AI Actions)
-- ==========================================

-- "Agent Mike" Output: Margin Calls
CREATE TABLE IF NOT EXISTS margin_calls (
    id SERIAL PRIMARY KEY,
    run_id INT REFERENCES sim_runs(id),
    date DATE,
    client_id VARCHAR(50) REFERENCES clients(client_id),
    client_name VARCHAR(100),
    funding_level_pct DECIMAL(10,2),
    call_amount DECIMAL(20,2),
    status VARCHAR(20) DEFAULT 'PENDING',
    ai_message TEXT -- The angry email drafted by the AI
);

-- "Agent Sarah" Output: Trades executed to fix the calls
CREATE TABLE IF NOT EXISTS trades (
    id SERIAL PRIMARY KEY,
    run_id INT REFERENCES sim_runs(id),
    date DATE,
    client_id TEXT,
    action VARCHAR(20),       -- 'SELL', 'REPO', 'REVERSE_REPO'
    asset_type VARCHAR(20),   -- 'GILT' or 'CASH'
    amount DECIMAL(20,2),     -- Amount traded
    rationale TEXT,           -- Sarah's reasoning logic
    status VARCHAR(20) DEFAULT 'EXECUTED'
);

-- ==========================================
-- 4. ANALYTICS VIEWS (For the Dashboard)
-- ==========================================

-- Master View combining Market, Health, and Agent Actions
CREATE OR REPLACE VIEW dashboard_master AS
SELECT 
    m.date,
    m.nominal_yield_10y as "Yield",
    m.regime as "Market Regime",
    
    -- Aggregate Funding Status (Assets / Liabilities)
    (SUM(i.total_assets) / NULLIF(SUM(l.pv_liabilities),0)) * 100 as "Funding_Level",
    
    -- Activity Counts
    (SELECT COUNT(*) FROM margin_calls mc WHERE mc.date = m.date) as "Margin_Calls",
    (SELECT COUNT(*) FROM trades t WHERE t.date = m.date) as "Trades"

FROM market_daily m
LEFT JOIN liabilities_daily l ON m.date = l.date
LEFT JOIN (
    SELECT date, client_id, SUM(quantity * market_price) as total_assets
    FROM collateral_inventory GROUP BY date, client_id
) i ON m.date = i.date AND l.client_id = i.client_id
GROUP BY m.date, m.nominal_yield_10y, m.regime
ORDER BY m.date ASC;
